SET sql_mode = '';

CREATE TABLE IF NOT EXISTS auctions (
  auctionId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  itemNO INT NOT NULL,
  startingBid DECIMAL(10, 2) NOT NULL,
  endTime DATETIME NOT NULL,
  
  FOREIGN KEY (itemNO) REFERENCES item(itemNO)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

SELECT * FROM auctions;

-- ALTER TABLE auctions DROP FOREIGN KEY auctions_ibfk_1;

-- ALTER TABLE auctions ADD CONSTRAINT fk_auction_item
-- FOREIGN KEY (itemNO) REFERENCES item(itemNO)
-- ON DELETE CASCADE
-- ON UPDATE CASCADE;