CREATE TABLE IF NOT EXISTS bids (
  bidId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  auctionId INT NOT NULL,
  userID INT NOT NULL,
  bidAmount DECIMAL(10, 2) NOT NULL,
  bidTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (auctionId) REFERENCES auctions(auctionId)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  FOREIGN KEY (userID) REFERENCES usertable(userID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

SELECT * FROM bids;
