name: Firebase Deploy

on:
  push:
    branches:
      - aditi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Firebase
        run: echo "Add your Firebase deploy command here"